[project]
name = "ansible-role-autorestic"
version = "2.3.0"
description = "Configure backups using autorestic."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-dev-tools>=25.5.0",
]
