- name: Remove restic, autorestic, configuration and crontab entry
  block:
    - name: Remove restic binary
      ansible.builtin.file:
        path: /usr/local/bin/restic
        state: absent

    - name: Remove autorestic binary
      ansible.builtin.file:
        path: /usr/local/bin/autorestic
        state: absent

    - name: Remove autorestic configuration file
      ansible.builtin.file:
        path: ~/.autorestic.yml
        state: absent

    - name: Remove autorestic crontab PATH
      ansible.builtin.cron:
        name: PATH
        env: true
        job: /usr/local/bin:/usr/bin:/bin
        state: absent

    - name: Remove autorestic crontab job
      ansible.builtin.cron:
        name: Configure autorestic crontab job
        minute: "*/5"
        job: autorestic -c ~/.autorestic.yml --ci cron > /tmp/autorestic.log 2>&1
        state: absent
  when: autorestic_state == 'absent'
