---
# removal tasks file for autorestic
- name: Remove autorestic binary
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ autorestic_install_directory.path }}"
    - /usr/local/bin/autorestic
  become: true

- name: Remove autorestic configuration file
  ansible.builtin.file:
    path: "{{ autorestic_config_file }}"
    state: absent

- name: Remove restic binary
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ autorestic_restic_install_directory.path }}"
    - /usr/local/bin/restic
  become: true

- name: Remove autorestic crontab
  when: autorestic_cron
  block:
    - name: Remove autorestic crontab PATH
      ansible.builtin.cron:
        name: PATH
        env: true
        job: /usr/local/bin:/usr/bin:/bin
        state: absent

    - name: Remove autorestic crontab job
      ansible.builtin.cron:
        name: Configure autorestic crontab job
        minute: "*/5"
        job: autorestic -c {{ autorestic_config_file }} --ci cron > /tmp/autorestic.log 2>&1
        state: absent
