---
- name: Converge
  hosts: molecule
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - name: Include dbrennand.autorestic
      ansible.builtin.include_role:
        name: dbrennand.autorestic
    - name: Include dbrennand.autorestic autorestic_state absent
      ansible.builtin.include_role:
        name: dbrennand.autorestic
      vars:
        autorestic_state: absent
